version: 0.2

phases:
  build:
    commands:
      - aws deploy push --application-name hoshi-at-kadai-app --s3-location s3://hoshi-at-kadai-bucket/artifact.zip --source src
artifacts:
  files:
    - '**/*'
  base-directory: src